#!/usr/bin/env python3
"""
Embed PNG icons as C byte arrays for Textures_GetOrCreateFromMemory.

Two modes:
  python3 gen_icon.py                  — embeds icon.png -> src/icon_png.h  (addon icon)
  python3 gen_icon.py --gear           — embeds icons/*.png -> src/gear_icons_png.h (gear slot fallbacks)
  python3 gen_icon.py [icon.png]       — embeds a single PNG -> src/icon_png.h

See lessons_learned.txt §3 for context on why this approach is used
(Textures_LoadFromResource is broken under MinGW/Proton).
"""
import sys
import os
import glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def make_array_name(filename: str) -> str:
    """'icons/helm.png' -> 'gear_icon_helm_png'"""
    base = os.path.splitext(os.path.basename(filename))[0]
    return f'gear_icon_{base}_png'


def embed_bytes(data: bytes, array_name: str, f) -> None:
    f.write(f'static const unsigned char {array_name}[] = {{\n    ')
    hex_bytes = [f'0x{b:02x}' for b in data]
    for i, h in enumerate(hex_bytes):
        f.write(h)
        if i < len(hex_bytes) - 1:
            f.write(', ')
        if (i + 1) % 16 == 0:
            f.write('\n    ')
    f.write(f'\n}};\n\n')


def embed_single(src_path: str, out_path: str, array_name: str) -> None:
    data = open(src_path, 'rb').read()
    with open(out_path, 'w') as f:
        f.write('#pragma once\n\n')
        embed_bytes(data, array_name, f)
        f.write(f'static const unsigned int {array_name}_len = {len(data)};\n')
    print(f'Success: wrote {len(data)} bytes -> {out_path}')


def embed_gear_icons(icons_dir: str, out_path: str) -> None:
    pngs = sorted(glob.glob(os.path.join(icons_dir, '*.png')))
    if not pngs:
        print(f'ERROR: no PNG files found in {icons_dir}')
        sys.exit(1)

    entries = []
    for png in pngs:
        data = open(png, 'rb').read()
        name = os.path.basename(png)
        arr  = make_array_name(name)
        key  = f'icons/{name}'
        entries.append((key, arr, data))
        print(f'  {name}: {len(data)} bytes')

    with open(out_path, 'w') as f:
        f.write('#pragma once\n')
        f.write('/* Auto-generated by gen_icon.py --gear — do not edit */\n\n')

        for key, arr, data in entries:
            embed_bytes(data, arr, f)

        f.write('struct GearIconEntry { const char* key; const unsigned char* data; unsigned int len; };\n')
        f.write('static const GearIconEntry GEAR_ICONS[] = {\n')
        for key, arr, data in entries:
            f.write(f'    {{ "{key}", {arr}, {len(data)} }},\n')
        f.write('};\n')
        f.write('static const int GEAR_ICONS_COUNT = (int)(sizeof(GEAR_ICONS)/sizeof(GEAR_ICONS[0]));\n')

    total = sum(len(d) for _, _, d in entries)
    print(f'Success: {len(entries)} icons, {total} bytes total -> {out_path}')


if __name__ == '__main__':
    src_dir = os.path.join(SCRIPT_DIR, 'src')
    os.makedirs(src_dir, exist_ok=True)

    if '--gear' in sys.argv:
        icons_dir = os.path.join(SCRIPT_DIR, 'icons')
        if not os.path.isdir(icons_dir):
            print(f'ERROR: icons/ directory not found at {icons_dir}')
            sys.exit(1)
        embed_gear_icons(icons_dir, os.path.join(src_dir, 'gear_icons_png.h'))
    else:
        src = sys.argv[1] if len(sys.argv) > 1 else 'icon.png'
        if not os.path.exists(src):
            print(f'ERROR: {src} not found.')
            print('Place your icon PNG in the project root and re-run:')
            print('  python3 gen_icon.py icon.png')
            sys.exit(1)
        embed_single(src, os.path.join(src_dir, 'icon_png.h'), 'icon_png')
        print()
        print('Then in src/addon.cpp:')
        print('  1. Uncomment #include "icon_png.h"')
        print('  2. Set HAS_ICON = true')
        print('  3. Rebuild')
