#!/usr/bin/env python3
"""
Parse sc_builds_full.json for all weapon slot item IDs, query the GW2 API for
their types, and generate src/api/weapon_type_db.h.

Run this after scraping (or as part of build.sh --regen).
Usage: python3 build_weapon_db.py [--out <header_path>]
"""

import argparse
import json
import time
from pathlib import Path

import requests

SCRIPT_DIR  = Path(__file__).parent
DEFAULT_JSON = SCRIPT_DIR / ".." / "sc_builds_full.json"
DEFAULT_OUT  = SCRIPT_DIR / ".." / "src" / "api" / "weapon_type_db.h"
GW2_API      = "https://api.guildwars2.com"
WEAPON_SLOTS = {"WeaponA1", "WeaponA2", "WeaponB1", "WeaponB2"}

# GW2 API type → display name (normalise "Harpoon" to "Spear" since GW2
# labels the land weapon "Spear" while the API historically says "Harpoon")
TYPE_DISPLAY: dict[str, str] = {
    "Harpoon": "Spear",   # land Spear (SotO) and underwater Harpoon share the slot
}


def collect_ids(json_path: Path) -> list[int]:
    builds = json.loads(json_path.read_text(encoding="utf-8"))
    ids: set[int] = set()
    for build in builds:
        for item in build.get("gear", {}).get("items", []):
            if item.get("slot") in WEAPON_SLOTS and item.get("item_id"):
                ids.add(int(item["item_id"]))
    return sorted(ids)


def fetch_types(ids: list[int]) -> dict[int, str]:
    result: dict[int, str] = {}
    batch_size = 200
    for start in range(0, len(ids), batch_size):
        batch = ids[start : start + batch_size]
        ids_param = ",".join(str(i) for i in batch)
        resp = requests.get(f"{GW2_API}/v2/items?ids={ids_param}", timeout=30)
        resp.raise_for_status()
        for item in resp.json():
            iid = item.get("id", 0)
            raw_type = item.get("details", {}).get("type", "")
            if iid and raw_type:
                result[iid] = TYPE_DISPLAY.get(raw_type, raw_type)
        if start + batch_size < len(ids):
            time.sleep(0.3)
    return result


def generate_header(type_map: dict[int, str], out_path: Path) -> None:
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "/* Auto-generated by scraper/build_weapon_db.py — do not edit manually. */",
        "/* Maps SC reference weapon item IDs to GW2 weapon type strings.        */",
        "/* Re-generate: cd scraper && python3 build_weapon_db.py                */",
        "namespace WeaponTypeDB {",
        "inline const char* GetType(uint32_t id) noexcept {",
        "    switch (id) {",
    ]
    for iid, itype in sorted(type_map.items()):
        lines.append(f'        case {iid}: return "{itype}";')
    lines += [
        "        default: return nullptr;",
        "    }",
        "}",
        "} /* namespace WeaponTypeDB */",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", default=str(DEFAULT_JSON))
    ap.add_argument("--out",  default=str(DEFAULT_OUT))
    args = ap.parse_args()

    json_path = Path(args.json)
    out_path  = Path(args.out)

    print("Collecting weapon item IDs from %s ..." % json_path)
    ids = collect_ids(json_path)
    print("  %d unique weapon item IDs" % len(ids))

    print("Fetching types from GW2 API ...")
    type_map = fetch_types(ids)
    print("  %d types resolved" % len(type_map))
    for iid, t in sorted(type_map.items()):
        print("    %7d  %s" % (iid, t))

    missing = set(ids) - set(type_map)
    if missing:
        print("  WARN: no type for IDs: %s" % sorted(missing))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    generate_header(type_map, out_path)
    print("Written: %s" % out_path)


if __name__ == "__main__":
    main()
