#pragma once
#include <cstdint>

/* Auto-generated by scraper/build_weapon_db.py — do not edit manually. */
/* Maps SC reference weapon item IDs to GW2 weapon type strings.        */
/* Re-generate: cd scraper && python3 build_weapon_db.py                */
namespace WeaponTypeDB {
inline const char* GetType(uint32_t id) noexcept {
    switch (id) {
        default: return nullptr;
    }
}
} /* namespace WeaponTypeDB */
