// Auto-generated by tools/generate_offline_db.py -- do not edit
// Revenant Legend swap skill ID → name mapping
// Source: GW2 API /v2/skills
#pragma once
#include <cstdint>
#include <cstring>

namespace OfflineData {

struct LegendEntry {
    uint32_t id;
    const char* name;
    const char* code;  /* Elite specialization code, empty for core legends */
};

inline constexpr LegendEntry LEGENDS[] = {
    {28085, "Legendary Dragon Stance",    ""},
    {28134, "Legendary Assassin Stance",  ""},
    {28419, "Legendary Dwarf Stance",     ""},
    {28494, "Legendary Demon Stance",     ""},
    {41858, "Legendary Renegade Stance",  "Renegade"},
    {28195, "Legendary Centaur Stance",   ""},
    {62749, "Legendary Alliance",         "Vindicator"},
    {76610, "Legendary Entity Stance",    "Conduit"},
    {46409, "Legendary Renegade Stance",  "Renegade"},
};

inline constexpr size_t LEGEND_COUNT = 9;

inline const LegendEntry* FindLegend(uint32_t id) {
    for (const auto& l : LEGENDS) {
        if (l.id == id) return &l;
    }
    return nullptr;
}

inline const char* GetLegendName(uint32_t id) {
    const auto* entry = FindLegend(id);
    return entry ? entry->name : "Unknown Legend";
}

inline const char* GetLegendCode(uint32_t id) {
    const auto* entry = FindLegend(id);
    return entry ? entry->code : "";
}

/* Match legend by name (case-insensitive, partial match) or common short name */
inline const LegendEntry* FindLegendByName(const char* name) {
    if (!name || !name[0]) return nullptr;

    auto lc = [](const char* s, char* buf, size_t sz) {
        size_t i = 0;
        for (; s[i] && i < sz - 1; i++)
            buf[i] = (s[i] >= 'A' && s[i] <= 'Z') ? s[i] + 32 : s[i];
        buf[i] = '\0';
    };

    char buf[64]; lc(name, buf, sizeof(buf));

    for (const auto& l : LEGENDS) {
        char lb[64]; lc(l.name, lb, sizeof(lb));
        if (strstr(lb, buf)) return &l;
    }
    for (const auto& l : LEGENDS) {
        if (l.code && l.code[0]) {
            char cb[32]; lc(l.code, cb, sizeof(cb));
            if (strstr(cb, buf)) return &l;
        }
    }

    static const char* SHORT_NAMES[9] = {
        "glint", "shiro", "jalis", "mallyx",
        "kalla", "ventari", "alliance", "conduit", "kalla",
    };
    for (int si = 0; si < 9; si++) {
        if (strstr(SHORT_NAMES[si], buf) || strstr(buf, SHORT_NAMES[si]))
            return &LEGENDS[si];
    }
    return nullptr;
}

} /* namespace OfflineData */
