// Auto-generated by tools/generate_offline_db.py -- do not edit
// Revenant Legend skill ID → name mapping
// Source: GW2 API /v2/skills
#pragma once
#include <cstdint>

namespace OfflineData {

struct LegendEntry {
    uint32_t id;
    const char* name;
    const char* code;  /* Elite specialization code, empty for core legends */
};

inline constexpr LegendEntry LEGENDS[] = {
    {28085, "Legendary Assassin Skill", ""},
    {28134, "Legendary Centaur Skill", ""},
    {28427, "Legendary Dwarf Skill", ""},
    {28494, "Legendary Demon Skill", ""},
    {26937, "Legendary Dragon Skill", "Renegade"},
    {27220, "Legendary Alliance Skill", "Renegade"},
    {46409, "Legendary Enchantment Skill", "Vindicator"},
    {62891, "Legendary Facet Skill", "Herald"},
    {78845, "Legendary Aura Skill", "Conduit"},
};

inline constexpr size_t LEGEND_COUNT = 9;

inline const LegendEntry* FindLegend(uint32_t id) {
    for (const auto& l : LEGENDS) {
        if (l.id == id) return &l;
    }
    return nullptr;
}

inline const char* GetLegendName(uint32_t id) {
    const auto* entry = FindLegend(id);
    return entry ? entry->name : "Unknown Legend";
}

inline const char* GetLegendCode(uint32_t id) {
    const auto* entry = FindLegend(id);
    return entry ? entry->code : "";
}

} /* namespace OfflineData */
