// Auto-generated by tools/generate_offline_db.py -- do not edit
// Ranger Pet ID → name mapping
// Source: GW2 API /v2/pets
#pragma once
#include <cstdint>

namespace OfflineData {

struct PetEntry {
    uint32_t id;
    const char* name;
    bool aquatic;
};

inline constexpr PetEntry PETS[] = {
    /* Terrestrial - Ferocious */
    {56, "Juvenile Wolf", false},
    {57, "Juvenile Wolf", false},
    {58, "Juvenile Brown Bear", false},
    {59, "Juvenile Spider", false},
    {60, "Juvenile Lynx", false},
    {61, "Juvenile Jaguar", false},
    {62, "Juvenile Moa", false},
    {63, "Juvenile Devourer", false},
    {64, "Juvenile Drake", false},
    {65, "Juvenile Pig", false},
    {66, "Juvenile Raven", false},
    {67, "Juvenile Shark", false},
    {68, "Juvenile Smokescale", false},
    {69, "Juvenile Jacaranda", false},
    {70, "Juvenile Fern Hound", false},
    /* Terrestrial - Sturdy */
    {71, "Juvenile Bear", false},
    {72, "Juvenile Black Bear", false},
    {73, "Juvenile Polar Bear", false},
    {74, "Juvenile Dragon Lizard", false},
    {75, "Juvenile Rock Gazelle", false},
    /* Terrestrial - Support */
    {76, "Juvenile Pink Moa", false},
    {77, "Juvenile Blue Moa", false},
    {78, "Juvenile Red Moa", false},
    {79, "Juvenile Black Moa", false},
    {80, "Juvenile White Moa", false},
    {81, "Juvenile Electric Wyvern", false},
    {82, "Juvenile Fire Wyvern", false},
    {83, "Juvenile Ice Wyvern", false},
    /* Terrestrial - Elite/Special */
    {84, "Juvenile Tiger", false},
    {85, "Juvenile Hawk", false},
    {86, "Juvenile Crocodile", false},
    {87, "Juvenile Phoenix", false},
    {88, "Juvenile Jellyfish", false},
    {89, "Juvenile Warthog", false},
    {90, "Juvenile Tiger", false},
    {91, "Juvenile Shark", false},
    /* Aquatic */
    {92, "Juvenile Blue Eel", true},
    {93, "Juvenile Red Eel", true},
    {94, "Juvenile Tiger", true},
    {95, "Juvenile Shark", true},
    {96, "Juvenile Orca", true},
    {97, "Juvenile Manta Ray", true},
    {98, "Juvenile Sea Spider", true},
    {99, "Juvenile Jellyfish", true},
    {100, "Juvenile Crab", true},
    /* Mount-linked (Soulbeast) */
    {101, "Juvenile Wyvern", false},
    {102, "Juvenile Griffon", false},
    {103, "Juvenile Raptor", false},
    {104, "Juvenile Springer", false},
    {105, "Juvenile Skimmer", false},
    {106, "Juvenile Jackal", false},
};

inline constexpr size_t PET_COUNT = 51;

inline const PetEntry* FindPet(uint32_t id) {
    for (const auto& p : PETS) {
        if (p.id == id) return &p;
    }
    return nullptr;
}

inline const char* GetPetName(uint32_t id) {
    const auto* entry = FindPet(id);
    return entry ? entry->name : "Unknown Pet";
}

inline bool IsAquaticPet(uint32_t id) {
    const auto* entry = FindPet(id);
    return entry ? entry->aquatic : false;
}

} /* namespace OfflineData */
