// Auto-generated by tools/generate_offline_db.py -- do not edit
// Specialization names from GW2 API cache
#pragma once
#include <cstdint>

namespace OfflineData {

struct SpecEntry {
    uint32_t id;
    const char* name;
    const char* profession;
    const char* icon;
    bool elite;
};

inline constexpr SpecEntry SPECS[] = {
    {1, "Dueling", "Mesmer", "https://render.guildwars2.com/file/43C5400906A104C60F30DFE0A145D1E767353573/1012003.png", false},
    {2, "Death Magic", "Necromancer", "https://render.guildwars2.com/file/16663C1CDF532AB0DCC0CB08951DD2F49351D5D4/1012008.png", false},
    {3, "Invocation", "Revenant", "https://render.guildwars2.com/file/2C4DCE5C0C255F32B51DCF9E4360106823EAF926/1012018.png", false},
    {4, "Strength", "Warrior", "https://render.guildwars2.com/file/0D48C40A1C042B0BC6DAA4B91AB272E5E90C934C/1012032.png", false},
    {5, "Druid", "Ranger", "https://render.guildwars2.com/file/BE10CB10D8446208729934F3F1BD3A54BEED9AD6/1012013.png", true},
    {6, "Explosives", "Engineer", "https://render.guildwars2.com/file/7DCC0CC4CE0E550C36F37F65469FF3103E2F2DA5/1011989.png", false},
    {7, "Daredevil", "Thief", "https://render.guildwars2.com/file/F1985D4E1CE043D7145E030C0AC4CFDABED73A59/1012025.png", true},
    {8, "Marksmanship", "Ranger", "https://render.guildwars2.com/file/80FEB75663DAE60BAC59495671261C206C0BAFC3/1012014.png", false},
    {9, "Retribution", "Revenant", "https://render.guildwars2.com/file/70B5F7E02769762D5FEE056D0136093BF3F580FF/1029933.png", false},
    {10, "Domination", "Mesmer", "https://render.guildwars2.com/file/4B61EA5997709A5DC1E46FF50CEDF2A13C1F0C3D/1012002.png", false},
    {11, "Tactics", "Warrior", "https://render.guildwars2.com/file/373162E8DED2793801194E622FEDEF2DBBDA6F10/1012033.png", false},
    {12, "Salvation", "Revenant", "https://render.guildwars2.com/file/0F0144B0E123163E0454B0C3D532282555BE7CE5/1029934.png", false},
    {13, "Valor", "Guardian", "https://render.guildwars2.com/file/F8A95D6D3904A1F6430CF2D33A02FDF2A6132037/1011997.png", false},
    {14, "Corruption", "Revenant", "https://render.guildwars2.com/file/FF4CBE97A807903DF3495E0ECC380E080291C698/1029931.png", false},
    {15, "Devastation", "Revenant", "https://render.guildwars2.com/file/C95CAFC4DC0D2AF5DB0C66CB0E0B0FA699E45D6C/1029932.png", false},
    {16, "Radiance", "Guardian", "https://render.guildwars2.com/file/16A05D047DFC0828D0E496F46FD8B20F97B42EB3/1011996.png", false},
    {17, "Water", "Elementalist", "https://render.guildwars2.com/file/A3D60C0EBE0B33907505C7DED0FD4E4DE565250F/1011987.png", false},
    {18, "Berserker", "Warrior", "https://render.guildwars2.com/file/B706475993F16D0BD7DFDF3BB30AA144051CDC94/1029935.png", true},
    {19, "Blood Magic", "Necromancer", "https://render.guildwars2.com/file/D1D9C63AD9CC05FC1B19970556B0C1E0ADD77905/1012006.png", false},
    {20, "Shadow Arts", "Thief", "https://render.guildwars2.com/file/B62E5512754BEB1D0116B1DB3B6FA0ECA4DD630C/1012027.png", false},
    {21, "Tools", "Engineer", "https://render.guildwars2.com/file/2CBB5AE626A47DF79C9294ECA61D77922A123600/1011993.png", false},
    {22, "Defense", "Warrior", "https://render.guildwars2.com/file/5F0B793A5479007078067CD71D0E01B30602189B/1012030.png", false},
    {23, "Inspiration", "Mesmer", "https://render.guildwars2.com/file/BCC2C316C4FC2823679E0FD062C5A87E96E460CC/1012004.png", false},
    {24, "Illusions", "Mesmer", "https://render.guildwars2.com/file/A6D57C63D9EFB3FE75C9DAF8CBE603D8F45A635F/1012005.png", false},
    {25, "Nature Magic", "Ranger", "https://render.guildwars2.com/file/DC7A387D9AB3EACCDA35AEA872E4EA1007139612/1012015.png", false},
    {26, "Earth", "Elementalist", "https://render.guildwars2.com/file/BA6BC962A7ABA1330B3AC4141299397C0036559F/1011985.png", false},
    {27, "Dragonhunter", "Guardian", "https://render.guildwars2.com/file/736DB02E6DA2ACFAD3B9B0F4655113AD214FFA40/1011994.png", true},
    {28, "Deadly Arts", "Thief", "https://render.guildwars2.com/file/38F6FA9A5D04CEC605AF6E5D994119281A38A9FA/1012026.png", false},
    {29, "Alchemy", "Engineer", "https://render.guildwars2.com/file/2AD4CD9B66F349A6CBC006A14848CF531E97396D/1011988.png", false},
    {30, "Skirmishing", "Ranger", "https://render.guildwars2.com/file/A026F49FF905C0F8AFAC6EDFDE281AABE1912459/1012016.png", false},
    {31, "Fire", "Elementalist", "https://render.guildwars2.com/file/B4BDAB2452DEF1A34615DDC4F30A157DADC743C5/1011986.png", false},
    {32, "Beastmastery", "Ranger", "https://render.guildwars2.com/file/02D851E1D7186112786D0F67910B58FACB5CCCF6/1012012.png", false},
    {33, "Wilderness Survival", "Ranger", "https://render.guildwars2.com/file/BEDA4B0CCD2E6F5F5C64509D67D3454E47D019F3/1012017.png", false},
    {34, "Reaper", "Necromancer", "https://render.guildwars2.com/file/530A582BD864B73AF5CC6C44F9C61954322D9A15/1012009.png", true},
    {35, "Critical Strikes", "Thief", "https://render.guildwars2.com/file/1CDB2736E6CAF79A1B549B06CDED717B3418F7B1/1012024.png", false},
    {36, "Arms", "Warrior", "https://render.guildwars2.com/file/03754E10970D0C68D76A1955245D7CB39AA21E59/1012029.png", false},
    {37, "Arcane", "Elementalist", "https://render.guildwars2.com/file/C7F4C199EC07D0E6CC9417C6F53F53FDD3F92947/1011984.png", false},
    {38, "Firearms", "Engineer", "https://render.guildwars2.com/file/67A2C92B59BC94EDD3D857C2DD18E1A02A631F98/1011990.png", false},
    {39, "Curses", "Necromancer", "https://render.guildwars2.com/file/C8E1A81601C3D5AC10285505E9F730621C3357CD/1012007.png", false},
    {40, "Chronomancer", "Mesmer", "https://render.guildwars2.com/file/D9C960059A69F4DB6604DAD6AF06D0F940E76754/1012001.png", true},
    {41, "Air", "Elementalist", "https://render.guildwars2.com/file/D3DB62FF6055021A717F3C6A0C19502F2C4EC1FF/1011983.png", false},
    {42, "Zeal", "Guardian", "https://render.guildwars2.com/file/479676FC6349C7A12D429B685F0D4205ABFF2F94/1011999.png", false},
    {43, "Scrapper", "Engineer", "https://render.guildwars2.com/file/FEB1B8C559DDB5A04F9C0579F741080259FEF841/1011991.png", true},
    {44, "Trickery", "Thief", "https://render.guildwars2.com/file/06BF06CDA7150617C5E075265C1E2F15E84B3D64/1012028.png", false},
    {45, "Chaos", "Mesmer", "https://render.guildwars2.com/file/7FD4DF076AFB31793EFA07220B35B427B3D406C3/1012000.png", false},
    {46, "Virtues", "Guardian", "https://render.guildwars2.com/file/E165042F92999B3BEFA91E280CB807F62EF30218/1011998.png", false},
    {47, "Inventions", "Engineer", "https://render.guildwars2.com/file/91F9AF48FA1DDEB66A449095A4E1A6E901AE203D/1011992.png", false},
    {48, "Tempest", "Elementalist", "https://render.guildwars2.com/file/D1970ABC09D07B4275C7E47DDD0EDC0F4CFC050C/1029930.png", true},
    {49, "Honor", "Guardian", "https://render.guildwars2.com/file/A4C0E39152B005EE226DA56D010DEEABB1ADBF2B/1011995.png", false},
    {50, "Soul Reaping", "Necromancer", "https://render.guildwars2.com/file/A5A95CB5FADD99F59E07400907F0782B659574A9/1012010.png", false},
    {51, "Discipline", "Warrior", "https://render.guildwars2.com/file/D10B771D01C85DA404472EE90F35EF15B0B36240/1012031.png", false},
    {52, "Herald", "Revenant", "https://render.guildwars2.com/file/78496E9E95C46527F8E0B974530A07A017DC9B79/1058520.png", true},
    {53, "Spite", "Necromancer", "https://render.guildwars2.com/file/2D34377B04051FFDCDB553C7DCDABCD5DFBB68D7/1012011.png", false},
    {54, "Acrobatics", "Thief", "https://render.guildwars2.com/file/E109FF4E65CD3FA4AAC20E9D219C4D5207E1E461/1012023.png", false},
    {55, "Soulbeast", "Ranger", "https://render.guildwars2.com/file/0AA4A2C62C4F2D0E0D59DBEE9C63EB4AF472F0C5/1769893.png", true},
    {56, "Weaver", "Elementalist", "https://render.guildwars2.com/file/02FAA82BF2F5BF3E3AD89BCF05FF56B4C86139F4/1769888.png", true},
    {57, "Holosmith", "Engineer", "https://render.guildwars2.com/file/F41CDEE4603FC0741669A7F2A7E977D36123DF7C/1769889.png", true},
    {58, "Deadeye", "Thief", "https://render.guildwars2.com/file/F93EF1717238E9ACC1CA330D4416D324AE08585D/1769895.png", true},
    {59, "Mirage", "Mesmer", "https://render.guildwars2.com/file/6403ECA8E6C1683E2C9D075A39C154ED3A7C04A1/1769891.png", true},
    {60, "Scourge", "Necromancer", "https://render.guildwars2.com/file/1407ADE7787A6BF6E457F5FA6DFA1062A5FA93FD/1769892.png", true},
    {61, "Spellbreaker", "Warrior", "https://render.guildwars2.com/file/06DFB7E3F267ADD0BB43C7383251343858371D02/1769896.png", true},
    {62, "Firebrand", "Guardian", "https://render.guildwars2.com/file/6D18B2D3EE0BFA0E4BC851A7D3C39D4330250916/1769890.png", true},
    {63, "Renegade", "Revenant", "https://render.guildwars2.com/file/0152279F7DD0FCFA21F2D1CC17DE21B2BD58EFF3/1769894.png", true},
    {64, "Harbinger", "Necromancer", "https://render.guildwars2.com/file/75B05DF5ED51D0153838EC134CEFCFC80D97DA0E/2479304.png", true},
    {65, "Willbender", "Guardian", "https://render.guildwars2.com/file/117F4659C3AD0AF6625D51013F03D541BEF2E8A6/2479302.png", true},
    {66, "Virtuoso", "Mesmer", "https://render.guildwars2.com/file/7B0F5E48320F35C0C6A2013ACF63F4C17B1105A5/2479303.png", true},
    {67, "Catalyst", "Elementalist", "https://render.guildwars2.com/file/1DF8CD361899081107B504A02B01C9B3B3645970/2491507.png", true},
    {68, "Bladesworn", "Warrior", "https://render.guildwars2.com/file/9D0ADEDFDEACCCD2B27103A944B1E7F6C21DCBE2/2491509.png", true},
    {69, "Vindicator", "Revenant", "https://render.guildwars2.com/file/4FE40FD1ECD6C4EC45A32A2A740AC2E2A147E04F/2491508.png", true},
    {70, "Mechanist", "Engineer", "https://render.guildwars2.com/file/F86CDF34404C0B5A01CD0CBB9D7D0DC1D8CC48CF/2503608.png", true},
    {71, "Specter", "Thief", "https://render.guildwars2.com/file/E915E494C64037C93AB53FB6F2D414B468DBCA48/2503610.png", true},
    {72, "Untamed", "Ranger", "https://render.guildwars2.com/file/D219A813B5312BA9D1D10A74C10E9E5F3F54936B/2503609.png", true},
    {73, "Troubadour", "Mesmer", "https://render.guildwars2.com/file/0FDD99E8B7A7FB4B06186C0756E02C0515520F75/3679899.png", true},
    {74, "Paragon", "Warrior", "https://render.guildwars2.com/file/B915D599CB40733130F7121B5CDE0BE42ED9E06C/3679904.png", true},
    {75, "Amalgam", "Engineer", "https://render.guildwars2.com/file/67AA599996662C5BA8427FA7BA6FF8B4ED221B0D/3679897.png", true},
    {76, "Ritualist", "Necromancer", "https://render.guildwars2.com/file/9064C22D08E4A7686FFB0256DDF42B97055EB144/3679900.png", true},
    {77, "Antiquary", "Thief", "https://render.guildwars2.com/file/569D3C9A9E7121939844809F0D05E81480C8F6F8/3679903.png", true},
    {78, "Galeshot", "Ranger", "https://render.guildwars2.com/file/1E0DE9DF219380B3DD15AD35466461C935930515/3679901.png", true},
    {79, "Conduit", "Revenant", "https://render.guildwars2.com/file/63DD70A26845681B9B993A51987F60A2F7970C52/3679902.png", true},
    {80, "Evoker", "Elementalist", "https://render.guildwars2.com/file/A80E0721636B027711E408BF0ADFDCD3330920AA/3679896.png", true},
    {81, "Luminary", "Guardian", "https://render.guildwars2.com/file/034C203DBD60CFF19D3D5CE9E71B27CA0103F50D/3679898.png", true},
};
inline constexpr size_t SPEC_COUNT = 81;

inline const SpecEntry* FindSpec(uint32_t id) {
    for (const auto& s : SPECS) {
        if (s.id == id) return &s;
    }
    return nullptr;
}

} /* namespace OfflineData */