#pragma once
#include <cstdint>

/* Auto-generated by scraper/build_weapon_db.py — do not edit manually. */
/* Maps SC reference weapon item IDs to GW2 weapon type strings.        */
/* Re-generate: cd scraper && python3 build_weapon_db.py                */
namespace WeaponTypeDB {
inline const char* GetType(uint32_t id) noexcept {
    switch (id) {
        case 39616: return "Default";
        case 39619: return "Default";
        case 39620: return "Default";
        case 39621: return "Default";
        case 46759: return "Axe";
        case 46760: return "Dagger";
        case 46761: return "Focus";
        case 46762: return "Greatsword";
        case 46763: return "Hammer";
        case 46764: return "Spear";
        case 46765: return "LongBow";
        case 46766: return "Mace";
        case 46767: return "Pistol";
        case 46768: return "Rifle";
        case 46769: return "Scepter";
        case 46770: return "Shield";
        case 46773: return "Staff";
        case 46774: return "Sword";
        case 47006: return "Axe";
        case 47007: return "Dagger";
        case 47014: return "Pistol";
        case 47020: return "Staff";
        case 47022: return "Torch";
        case 47024: return "Warhorn";
        case 67938: return "Sword";
        case 67948: return "Dagger";
        case 67951: return "Focus";
        case 70504: return "LongBow";
        case 70838: return "Sword";
        case 71387: return "Staff";
        case 72239: return "Pistol";
        case 73580: return "Spear";
        case 74179: return "Dagger";
        case 74569: return "ShortBow";
        case 75325: return "Warhorn";
        case 76271: return "Torch";
        case 76688: return "Scepter";
        case 76786: return "Mace";
        case 77122: return "Axe";
        case 84876: return "Sword";
        case 84912: return "Mace";
        case 84936: return "Dagger";
        case 84957: return "Shield";
        case 84973: return "Warhorn";
        case 85013: return "Torch";
        case 85019: return "Greatsword";
        case 85027: return "Scepter";
        case 85047: return "Axe";
        case 85051: return "Dagger";
        case 85112: return "Staff";
        case 85121: return "Greatsword";
        case 85254: return "Spear";
        case 85348: return "Rifle";
        case 86504: return "Mace";
        case 86505: return "Shield";
        case 86706: return "ShortBow";
        case 95781: return "Axe";
        case 96044: return "Mace";
        case 96525: return "Spear";
        case 96528: return "ShortBow";
        case 96821: return "Dagger";
        case 97508: return "Pistol";
        case 97752: return "Torch";
        default: return nullptr;
    }
}
} /* namespace WeaponTypeDB */
