#!/usr/bin/env python3
"""
Embed sc_builds_full.json as a C++ header file.
"""
import json

INPUT_FILE = "/home/todd/gw2-build-coaches/gw2-build-coach-new-modified/sc_builds_full.json"
OUTPUT_FILE = "/home/todd/gw2-build-coaches/Accessibuilds/src/sc_builds_offline.h"

def main():
    print(f"Loading {INPUT_FILE}...")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        builds = json.load(f)
    
    print(f"Loaded {len(builds)} builds")
    
    # Re-serialize with consistent formatting
    json_str = json.dumps(builds, indent=2, ensure_ascii=False)
    
    # Escape for C string literal
    json_str = json_str.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n"')
    
    header = f'''// Auto-generated by tools/embed_builds.py -- do not edit
// Embedded Snow Crows reference builds for offline viewing
// Source: sc_builds_full.json ({len(builds)} builds)
#pragma once
#include <cstdint>

namespace OfflineData {{

inline const char* OFFLINE_BUILDS_JSON = 
"{json_str}";

inline constexpr size_t OFFLINE_BUILD_COUNT = {len(builds)};

}} /* namespace OfflineData */
'''
    
    print(f"Writing {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(header)
    
    print("Done!")

if __name__ == "__main__":
    main()
