#!/usr/bin/env python3
"""
Embed sc_builds_full.json as a C++ header file.
If the file doesn't exist, embed an empty JSON array.
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
INPUT_FILE = os.path.join(REPO_DIR, "sc_builds_full.json")
OUTPUT_FILE = os.path.join(REPO_DIR, "src", "sc_builds_offline.h")

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"  {INPUT_FILE} not found, embedding empty array")
        builds = []
    else:
        print(f"  Loading {INPUT_FILE}...")
        with open(INPUT_FILE, 'r', encoding='utf-8') as f:
            builds = json.load(f)
    
    print(f"  {len(builds)} builds")
    
    # Re-serialize with consistent formatting
    json_str = json.dumps(builds, indent=2, ensure_ascii=False)
    
    # Escape for C string literal
    json_str = json_str.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n"')
    
    header = f'''// Auto-generated by tools/embed_builds.py -- do not edit
// Embedded Snow Crows reference builds for offline viewing
// Source: sc_builds_full.json ({len(builds)} builds)
#pragma once
#include <cstdint>

namespace OfflineData {{

inline const char* OFFLINE_BUILDS_JSON = 
"{json_str}";

inline constexpr size_t OFFLINE_BUILD_COUNT = {len(builds)};

}} /* namespace OfflineData */
'''
    
    print(f"  Writing {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(header)
    
    print("  Done!")

if __name__ == "__main__":
    main()
