#!/usr/bin/env python3
"""
Fetch complete GW2 API data for offline mode.
Creates: spec_names.h, trait_names.h, skill_names.h with actual names.
"""
import json
import urllib.request
from collections import OrderedDict

OUTPUT_DIR = "/home/todd/gw2-build-coaches/Accessibuilds/src/api"
GW2_API_BASE = "https://api.guildwars2.com/v2"

def fetch_json(url):
    """Fetch JSON from URL with error handling."""
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return json.loads(resp.read().decode('utf-8'))
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return None

def escape_string(s):
    """Escape special characters for C string literals."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')

def generate_spec_names(specs):
    """Generate spec_names.h from specializations data."""
    lines = [
        "// Auto-generated by tools/fetch_offline_data.py -- do not edit",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace OfflineData {",
        "",
        "struct SpecEntry {",
        "    uint32_t id;",
        "    const char* name;",
        "    const char* profession;",
        "    const char* icon;",
        "    bool elite;",
        "};",
        "",
        f"inline constexpr SpecEntry SPECS[] = {{",
    ]
    
    for spec in sorted(specs, key=lambda x: x['id']):
        name = escape_string(spec.get('name', 'Unknown'))
        prof = escape_string(spec.get('profession', ''))
        icon = escape_string(spec.get('icon', ''))
        elite = 'true' if spec.get('elite', False) else 'false'
        lines.append(f"    {{{spec['id']}, \"{name}\", \"{prof}\", \"{icon}\", {elite}}},")
    
    lines.append("};")
    lines.append(f"inline constexpr size_t SPEC_COUNT = {len(specs)};")
    lines.append("")
    lines.append("inline const SpecEntry* FindSpec(uint32_t id) {")
    lines.append("    for (const auto& s : SPECS) {")
    lines.append("        if (s.id == id) return &s;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} /* namespace OfflineData */")
    
    return '\n'.join(lines)

def generate_trait_names(traits):
    """Generate trait_names.h from traits data."""
    lines = [
        "// Auto-generated by tools/fetch_offline_data.py -- do not edit",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace OfflineData {",
        "",
        "struct TraitEntry {",
        "    uint32_t id;",
        "    const char* name;",
        "    const char* icon;",
        "};",
        "",
        f"inline constexpr TraitEntry TRAITS[] = {{",
    ]
    
    for trait in sorted(traits, key=lambda x: x['id']):
        name = escape_string(trait.get('name', 'Unknown'))
        icon = escape_string(trait.get('icon', ''))
        lines.append(f"    {{{trait['id']}, \"{name}\", \"{icon}\"}},")
    
    lines.append("};")
    lines.append(f"inline constexpr size_t TRAIT_COUNT = {len(traits)};")
    lines.append("")
    lines.append("inline const TraitEntry* FindTrait(uint32_t id) {")
    lines.append("    for (const auto& t : TRAITS) {")
    lines.append("        if (t.id == id) return &t;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} /* namespace OfflineData */")
    
    return '\n'.join(lines)

def generate_skill_names(skills):
    """Generate skill_names.h from skills data."""
    lines = [
        "// Auto-generated by tools/fetch_offline_data.py -- do not edit",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace OfflineData {",
        "",
        "struct SkillEntry {",
        "    uint32_t id;",
        "    const char* name;",
        "    const char* icon;",
        "};",
        "",
        f"inline constexpr SkillEntry SKILLS[] = {{",
    ]
    
    for skill in sorted(skills, key=lambda x: x['id']):
        name = escape_string(skill.get('name', 'Unknown'))
        icon = escape_string(skill.get('icon', ''))
        lines.append(f"    {{{skill['id']}, \"{name}\", \"{icon}\"}},")
    
    lines.append("};")
    lines.append(f"inline constexpr size_t SKILL_COUNT = {len(skills)};")
    lines.append("")
    lines.append("inline const SkillEntry* FindSkill(uint32_t id) {")
    lines.append("    for (const auto& s : SKILLS) {")
    lines.append("        if (s.id == id) return &s;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} /* namespace OfflineData */")
    
    return '\n'.join(lines)

def main():
    print("Fetching GW2 API data...")
    
    # Fetch all specializations
    print("  Fetching specializations...")
    spec_ids = fetch_json(f"{GW2_API_BASE}/specializations?ids=all")
    if not spec_ids:
        print("Failed to fetch specialization IDs")
        return
    specs = []
    for i in range(0, len(spec_ids), 200):
        batch = spec_ids[i:i+200]
        result = fetch_json(f"{GW2_API_BASE}/specializations?ids={','.join(map(str, batch))}")
        if result:
            specs.extend(result)
        print(f"    Fetched {len(specs)}/{len(spec_ids)} specs")
    print(f"  Total specializations: {len(specs)}")
    
    # Fetch all traits
    print("  Fetching traits...")
    trait_ids = set()
    for spec in specs:
        trait_ids.update(spec.get('minor_traits', []))
        trait_ids.update(spec.get('major_traits', []))
    trait_ids = sorted(trait_ids)
    
    traits = []
    for i in range(0, len(trait_ids), 200):
        batch = trait_ids[i:i+200]
        result = fetch_json(f"{GW2_API_BASE}/traits?ids={','.join(map(str, batch))}")
        if result:
            traits.extend(result)
        print(f"    Fetched {len(traits)}/{len(trait_ids)} traits")
    print(f"  Total traits: {len(traits)}")
    
    # Fetch all skills
    print("  Fetching skills...")
    skill_ids = fetch_json(f"{GW2_API_BASE}/skills?ids=all")
    if not skill_ids:
        print("Failed to fetch skill IDs")
        return
    skills = []
    for i in range(0, len(skill_ids), 200):
        batch = skill_ids[i:i+200]
        result = fetch_json(f"{GW2_API_BASE}/skills?ids={','.join(map(str, batch))}")
        if result:
            skills.extend(result)
        print(f"    Fetched {len(skills)}/{len(skill_ids)} skills")
    print(f"  Total skills: {len(skills)}")
    
    # Generate header files
    print("\nGenerating header files...")
    
    print("  Writing spec_names.h...")
    with open(f"{OUTPUT_DIR}/spec_names.h", 'w', encoding='utf-8') as f:
        f.write(generate_spec_names(specs))
    
    print("  Writing trait_names.h...")
    with open(f"{OUTPUT_DIR}/trait_names.h", 'w', encoding='utf-8') as f:
        f.write(generate_trait_names(traits))
    
    print("  Writing skill_names.h...")
    with open(f"{OUTPUT_DIR}/skill_names.h", 'w', encoding='utf-8') as f:
        f.write(generate_skill_names(skills))
    
    print("\nDone! Generated files:")
    print(f"  - {OUTPUT_DIR}/spec_names.h ({len(specs)} specs)")
    print(f"  - {OUTPUT_DIR}/trait_names.h ({len(traits)} traits)")
    print(f"  - {OUTPUT_DIR}/skill_names.h ({len(skills)} skills)")

if __name__ == "__main__":
    main()
