#!/usr/bin/env python3
"""
Generate offline lookup tables from available data.
Uses scraper cache for specs, IDs for traits/skills (GW2Names fallback).
"""
import json
import os

SCRAPER_CACHE = "/home/todd/gw2-build-coaches/gw2-build-coach-new-modified/scraper/.scraper_cache"
OUTPUT_DIR = "/home/todd/gw2-build-coaches/Accessibuilds/src/api"

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def escape_string(s):
    """Escape special characters for C string literals."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')

def generate_spec_names(specs):
    """Generate spec_names.h from specializations data."""
    lines = [
        "// Auto-generated by tools/generate_offline_db.py -- do not edit",
        "// Specialization names from GW2 API cache",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace OfflineData {",
        "",
        "struct SpecEntry {",
        "    uint32_t id;",
        "    const char* name;",
        "    const char* profession;",
        "    const char* icon;",
        "    bool elite;",
        "};",
        "",
        f"inline constexpr SpecEntry SPECS[] = {{",
    ]
    
    for spec in sorted(specs, key=lambda x: x['id']):
        name = escape_string(spec.get('name', 'Unknown'))
        prof = escape_string(spec.get('profession', ''))
        icon = escape_string(spec.get('icon', ''))
        elite = 'true' if spec.get('elite', False) else 'false'
        lines.append(f"    {{{spec['id']}, \"{name}\", \"{prof}\", \"{icon}\", {elite}}},")
    
    lines.append("};")
    lines.append(f"inline constexpr size_t SPEC_COUNT = {len(specs)};")
    lines.append("")
    lines.append("inline const SpecEntry* FindSpec(uint32_t id) {")
    lines.append("    for (const auto& s : SPECS) {")
    lines.append("        if (s.id == id) return &s;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} /* namespace OfflineData */")
    
    return '\n'.join(lines)

def generate_trait_names(specs):
    """Generate trait_names.h with ID placeholders (GW2Names fallback)."""
    # Collect all unique trait IDs
    trait_ids = set()
    for spec in specs:
        trait_ids.update(spec.get('minor_traits', []))
        trait_ids.update(spec.get('major_traits', []))
    
    lines = [
        "// Auto-generated by tools/generate_offline_db.py -- do not edit",
        "// Trait IDs - names resolved via GW2Names (online) or ID display (offline)",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace OfflineData {",
        "",
        f"inline constexpr uint32_t TRAIT_IDS[] = {{",
    ]
    
    for tid in sorted(trait_ids):
        lines.append(f"    {tid},")
    
    lines.append("};")
    lines.append(f"inline constexpr size_t TRAIT_COUNT = {len(trait_ids)};")
    lines.append("")
    lines.append("// Check if a trait ID is in our known set")
    lines.append("inline bool IsKnownTrait(uint32_t id) {")
    lines.append("    for (const auto& t : TRAIT_IDS) {")
    lines.append("        if (t == id) return true;")
    lines.append("    }")
    lines.append("    return false;")
    lines.append("}")
    lines.append("")
    lines.append("} /* namespace OfflineData */")
    
    return '\n'.join(lines)

def generate_skill_names(professions):
    """Generate skill_names.h with ID list (GW2Names fallback)."""
    # Collect all unique skill IDs from palettes and training
    skill_ids = set()
    for prof in professions:
        for palette_id, skill_id in prof.get('skills_by_palette', []):
            skill_ids.add(skill_id)
        for track in prof.get('training', []):
            for entry in track.get('track', []):
                if entry.get('type') == 'Skill':
                    skill_ids.add(entry.get('skill_id'))
    
    lines = [
        "// Auto-generated by tools/generate_offline_db.py -- do not edit",
        "// Skill IDs - names resolved via GW2Names (online) or ID display (offline)",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace OfflineData {",
        "",
        f"inline constexpr uint32_t SKILL_IDS[] = {{",
    ]
    
    for sid in sorted(skill_ids):
        lines.append(f"    {sid},")
    
    lines.append("};")
    lines.append(f"inline constexpr size_t SKILL_COUNT = {len(skill_ids)};")
    lines.append("")
    lines.append("// Check if a skill ID is in our known set")
    lines.append("inline bool IsKnownSkill(uint32_t id) {")
    lines.append("    for (const auto& s : SKILL_IDS) {")
    lines.append("        if (s == id) return true;")
    lines.append("    }")
    lines.append("    return false;")
    lines.append("}")
    lines.append("")
    lines.append("} /* namespace OfflineData */")
    
    return '\n'.join(lines)

def main():
    print("Loading scraper cache data...")
    specs = load_json(os.path.join(SCRAPER_CACHE, "_gw2api_specializations.json"))
    professions = load_json(os.path.join(SCRAPER_CACHE, "_gw2api_professions.json"))
    
    print(f"Loaded {len(specs)} specializations")
    print(f"Loaded {len(professions)} professions")
    
    # Generate spec_names.h
    print("Generating spec_names.h...")
    spec_content = generate_spec_names(specs)
    with open(os.path.join(OUTPUT_DIR, "spec_names.h"), 'w', encoding='utf-8') as f:
        f.write(spec_content)
    
    # Generate trait_names.h
    print("Generating trait_names.h...")
    trait_content = generate_trait_names(specs)
    with open(os.path.join(OUTPUT_DIR, "trait_names.h"), 'w', encoding='utf-8') as f:
        f.write(trait_content)
    
    # Generate skill_names.h
    print("Generating skill_names.h...")
    skill_content = generate_skill_names(professions)
    with open(os.path.join(OUTPUT_DIR, "skill_names.h"), 'w', encoding='utf-8') as f:
        f.write(skill_content)
    
    print("\nDone! Generated files:")
    print(f"  - {OUTPUT_DIR}/spec_names.h ({len(specs)} specs with names)")
    print(f"  - {OUTPUT_DIR}/trait_names.h ({len(set(tid for s in specs for tid in s.get('minor_traits', []) + s.get('major_traits', [])))} trait IDs)")
    print(f"  - {OUTPUT_DIR}/skill_names.h (skill IDs)")

if __name__ == "__main__":
    main()
