// Auto-generated by tools/embed_builds.py -- do not edit
// Embedded Snow Crows reference builds for offline viewing
// Source: sc_builds_full.json (0 builds)
#pragma once
#include <cstdint>

namespace OfflineData {

inline const char* OFFLINE_BUILDS_JSON = 
"[]";

inline constexpr size_t OFFLINE_BUILD_COUNT = 0;

} /* namespace OfflineData */
